import solid_error from "../../assets/ToastIcons/icon-solid-error.png";
import solid_info from "../../assets/ToastIcons/icon-solid-info.png";
import solid_success from "../../assets/ToastIcons/icon-solid-success.png";
import solid_warning from "../../assets/ToastIcons/icon-solid-warning.png";
import alert_error from "../../assets/ToastIcons/alert-error.png";
import alert_info from "../../assets/ToastIcons/alert-info.png";
import alert_success from "../../assets/ToastIcons/alert-success.png";
import alert_warning from "../../assets/ToastIcons/alert-warning.png";
const data = [
  {
    id: 0,
    type: "error",
    title: "Bir sorun oluştu",
    description: "Description",
    link: undefined,
    icon: solid_error,
    lineType: "multiline",
    isDesktop: true,
  },
  {
    id: 1,
    type: "error",
    title: "Bir sorun oluştu",
    description: undefined,
    link: undefined,
    icon: solid_error,
    lineType: "singleline",
    isDesktop: true,
  },
  {
    id: 2,
    type: "info",
    title: "Title",
    description: "Description",
    link: undefined,
    icon: solid_info,
    lineType: "multiline",
    isDesktop: true,
  },
  {
    id: 3,
    type: "info",
    title: "Title",
    description: undefined,
    link: undefined,
    icon: solid_info,
    lineType: "singleline",
    isDesktop: true,
  },
  {
    id: 4,
    type: "success",
    title: "Title",
    description: "Description",
    link: "Link",
    icon: solid_success,
    lineType: "multiline",
    isDesktop: true,
  },
  {
    id: 5,
    type: "success",
    title: "Title",
    description: undefined,
    link: undefined,
    icon: solid_success,
    lineType: "singleline",
    isDesktop: true,
  },
  {
    id: 6,
    type: "warning",
    title: "Title",
    description: "Description",
    link: "Link",
    icon: solid_warning,
    lineType: "multiline",
    isDesktop: true,
  },
  {
    id: 7,
    type: "warning",
    title: "Title",
    description: undefined,
    link: undefined,
    icon: solid_warning,
    lineType: "singleline",
    isDesktop: true,
  },
  {
    id: 8,
    type: "error-mobile",
    title: "Bir sorun oluştu",
    description: "Description",
    link: "Link",
    icon: alert_error,
    lineType: "multiline",
    isDesktop: false,
  },
  {
    id: 9,
    type: "error-mobile",
    title: "Bir sorun oluştu",
    description: undefined,
    link: undefined,
    icon: alert_error,
    lineType: "singleline",
    isDesktop: false,
  },
  {
    id: 10,
    type: "info-mobile",
    title: "Title",
    description: "Description",
    link: undefined,
    icon: alert_info,
    lineType: "multiline",
    isDesktop: false,
  },
  {
    id: 11,
    type: "info-mobile",
    title: "title",
    description: undefined,
    link: undefined,
    icon: alert_info,
    lineType: "singleline",
    isDesktop: false,
  },
  {
    id: 12,
    type: "success-mobile",
    title: "Title",
    description: "Description",
    link: undefined,
    icon: alert_success,
    lineType: "multiline",
    isDesktop: false,
  },
  {
    id: 13,
    type: "success-mobile",
    title: "Title",
    description: undefined,
    link: undefined,
    icon: alert_success,
    lineType: "singleline",
    isDesktop: false,
  },
  {
    id: 14,
    type: "warning-mobile",
    title: "Title",
    description: "Description",
    link: undefined,
    icon: alert_warning,
    lineType: "multiline",
    isDesktop: false,
  },
  {
    id: 15,
    type: "warning-mobile",
    title: "Title",
    description: undefined,
    link: undefined,
    icon: alert_warning,
    lineType: "singleline",
    isDesktop: false,
  },
];
export default data;
